name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build # Changed from pnpm run build

      - name: Create directory structure for subdirectory deployment
        run: |
          mkdir -p deploy/gsha2025
          cp -r out/* deploy/gsha2025/
          echo "wriiiter.drewthekiiid.com" > deploy/CNAME

      - name: Add .nojekyll file
        run: touch ./deploy/.nojekyll # Prevents GitHub Pages from running Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: wriiiter.drewthekiiid.com
